/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.13.0
 *
 * Project: 'm2003-motor.Debug+M2003FC1AE' 
 * Target:  'Debug+M2003FC1AE' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M2003.h"



#endif /* RTE_COMPONENTS_H */
