[env:rpipico2w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
lib_extra_dirs = ..
lib_ignore = rpipico2w-single-actuator-testbench
