[env:rpipico2w]
platform = raspberrypi
board = rpipico2w
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
lib_extra_dirs = ..
lib_ignore = rpipico2w-single-actuator-testbench
