// Noncircular involute gear generator.
//
// Implements the algorithm of:
//   Uwe Bäsel, "Determining the geometry of noncircular gears for given
//   transmission function", arXiv:1905.02642v1 (2019).
//
// Given a transmission function psi(phi) with psi(2*pi) = 2*pi and
// psi'(phi) > 0, the program computes the complete tooth geometry of the
// drive gear (centrode X_P, negatively oriented) and the driven gear
// (centrode Xi_P, positively oriented) as generated by a rack-cutter with
// profile angle alpha, addendum h_a, dedendum h_f and fillet radius rho.
//
// Curve trimming (flank vs. addendum curve, and flank vs. fillet curve in
// the undercut case, eqs. (7.1)-(7.5)/(7.10)-(7.14)) is done with CGAL
// exact segment intersections.  The assembled tooth polygons are checked
// for simplicity and for mutual non-penetration over a set of meshing
// poses with CGAL polygon Boolean operations.

#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Polygon_2.h>
#include <CGAL/Polygon_with_holes_2.h>
#include <CGAL/Boolean_set_operations_2.h>
#include <CGAL/intersections.h>

#include <algorithm>
#include <cmath>
#include <complex>
#include <cstdio>
#include <functional>
#include <optional>
#include <stdexcept>
#include <string>
#include <vector>

using K       = CGAL::Exact_predicates_exact_constructions_kernel;
using EPoint  = K::Point_2;
using ESeg    = K::Segment_2;
using EPoly   = CGAL::Polygon_2<K>;
using EPwh    = CGAL::Polygon_with_holes_2<K>;

using cplx = std::complex<double>;
static const cplx I(0.0, 1.0);
static const double PI = 3.14159265358979323846;

// ---------------------------------------------------------------------------
// Transmission function psi and its first three derivatives.
// ---------------------------------------------------------------------------
struct TransFn {
    std::function<double(double)> psi, d1, d2, d3;
    std::string desc;
};

// psi(phi) = phi - (b/n) * sin(n*phi)  (the family used in the paper for n=1)
static TransFn sineTransmission(double b, int n, const std::string& desc) {
    TransFn f;
    f.psi = [b, n](double p) { return p - b / n * std::sin(n * p); };
    f.d1  = [b, n](double p) { return 1.0 - b * std::cos(n * p); };
    f.d2  = [b, n](double p) { return b * n * std::sin(n * p); };
    f.d3  = [b, n](double p) { return b * n * n * std::cos(n * p); };
    f.desc = desc;
    return f;
}

// ---------------------------------------------------------------------------
// Gear pair data and the curve formulas of the paper.
// ---------------------------------------------------------------------------
struct GearPair {
    TransFn f;
    int z;            // teeth (z1 = z2 since psi(2pi) = 2pi)
    double m;         // module
    double alpha;     // rack profile angle
    double ha, hf, rho;
    double a = 0.0;   // pivot distance, from (2.14)
    std::vector<double> chi;  // chi(k), k = 1..z, from (3.3)

    double w(double p) const {  // (2.12)
        double d1 = f.d1(p), d2 = f.d2(p);
        return std::hypot(d2, d1 * (1.0 + d1));
    }
    double integrand(double p) const {  // w/(1+psi')^2, integrand of (2.13)
        double d1 = f.d1(p);
        return w(p) / ((1.0 + d1) * (1.0 + d1));
    }
    // I(p0, p1), eq. (2.13): adaptive Simpson.
    double Ival(double p0, double p1) const {
        std::function<double(double, double, double, double, double, double, int)> rec =
            [&](double lo, double hi, double flo, double fmid, double fhi, double whole, int depth) -> double {
            double mid = 0.5 * (lo + hi);
            double lm = 0.5 * (lo + mid), rm = 0.5 * (mid + hi);
            double flm = integrand(lm), frm = integrand(rm);
            double left  = (mid - lo) / 6.0 * (flo + 4.0 * flm + fmid);
            double right = (hi - mid) / 6.0 * (fmid + 4.0 * frm + fhi);
            if (depth > 50 || std::fabs(left + right - whole) < 1e-13 * (1.0 + std::fabs(whole)))
                return left + right + (left + right - whole) / 15.0;
            return rec(lo, mid, flo, flm, fmid, left, depth + 1) +
                   rec(mid, hi, fmid, frm, fhi, right, depth + 1);
        };
        if (p0 == p1) return 0.0;
        // split into ~unit-length chunks for robustness
        int nseg = std::max(1, (int)std::ceil(std::fabs(p1 - p0)));
        double sum = 0.0;
        for (int s = 0; s < nseg; ++s) {
            double lo = p0 + (p1 - p0) * s / nseg;
            double hi = p0 + (p1 - p0) * (s + 1) / nseg;
            double flo = integrand(lo), fhi = integrand(hi), fm = integrand(0.5 * (lo + hi));
            double whole = (hi - lo) / 6.0 * (flo + 4.0 * fm + fhi);
            sum += rec(lo, hi, flo, fm, fhi, whole, 0);
        }
        return sum;
    }

    double r(double p) const { double d1 = f.d1(p); return a * d1 / (1.0 + d1); }   // (2.7)
    double R(double p) const { double d1 = f.d1(p); return a / (1.0 + d1); }        // (2.7)

    // lambda_{k,+-}(phi), eq. (3.4); s = +1 / -1 selects the flank.
    double lambda(int k, int s, double p) const {
        return s * PI * m / 4.0 - a * Ival(chi[k - 1], p);
    }
    // d lambda / d phi = -a * integrand  (3.12)
    double dlambda(double p) const { return -a * integrand(p); }

    // Oriented curvature of the centrode: kappa (3.21) for the drive gear,
    // kappa-tilde (4.14) for the driven gear.
    double curvature(bool driven, double p) const {
        double d1 = f.d1(p), d2 = f.d2(p), d3 = f.d3(p);
        double W = w(p);
        double bracket = driven
            ? d1 * d3 + d1 * d1 + d1 * d1 * d1 - d2 * d2                 // (4.10)
            : d1 * (d3 - d1 - d1 * d1) - 2.0 * d2 * d2;                  // (3.16)
        double c = (1.0 + d1);
        return c * c * c * bracket / (a * W * W * W);
    }

    // Centrode point: X_P (2.8) or Xi_P (2.9).
    cplx centrode(bool driven, double p) const {
        if (!driven) return r(p) * std::exp(-I * p);
        return -R(p) * std::exp(I * f.psi(p));
    }
    // Tangent unit vector: T (3.1) or T-tilde (4.2).
    cplx tangent(bool driven, double p) const {
        double d1 = f.d1(p), d2 = f.d2(p);
        cplx num(d2, -d1 * (1.0 + d1));
        cplx e = driven ? std::exp(I * f.psi(p)) : std::exp(-I * p);
        return num / w(p) * e;
    }
    // Outward unit normal of the gear blank.
    cplx outward(bool driven, double p) const {
        cplx t = tangent(driven, p);
        return driven ? -I * t : I * t;
    }
    // Offset (parallel) curve of the centrode, d > 0 outward:  (3.25)/(4.15).
    cplx offsetCurve(bool driven, double d, double p) const {
        return centrode(driven, p) + d * outward(driven, p);
    }
    // Flank curve X_F (3.7) / Xi_F (4.6).
    cplx flank(bool driven, int k, int s, double p) const {
        double lam = lambda(k, s, p);
        return centrode(driven, p) +
               lam * tangent(driven, p) * std::exp(I * (double)s * alpha) * std::cos(alpha);
    }
    // Fillet curve X_rho (3.29) / Xi_rho (4.18).  sigma = +1 drive, -1 driven.
    cplx fillet(bool driven, int k, int s, double p) const {
        double sg = driven ? -1.0 : 1.0;
        double lam = lambda(k, s, p);
        double sec = 1.0 / std::cos(alpha), tn = std::tan(alpha);
        cplx B = lam + sg * s * rho * sec - sg * (hf - rho) * (I - (double)s * tn);
        cplx t = tangent(driven, p);
        cplx XM = centrode(driven, p) + B * t;
        double sgnH = curvature(driven, p) >= 0.0 ? 1.0 : -1.0;  // sgn(h) = sgn(kappa)
        cplx N = -sg * sgnH * B * t / std::abs(B);
        return XM + rho * N;
    }
};

// ---------------------------------------------------------------------------
// Root finding helpers
// ---------------------------------------------------------------------------
// Solve lambda_{k,s}(phi) = c.  lambda is strictly decreasing.
static double lambdaInv(const GearPair& g, int k, int s, double c) {
    double chik = g.chi[k - 1];
    // initial guess from local arc-length rate
    double rate = g.a * g.integrand(chik);
    double p = chik + (s * PI * g.m / 4.0 - c) / rate;
    // expand bracket
    double lo = p, hi = p;
    double step = 0.25;
    while (g.lambda(k, s, lo) < c) { lo -= step; step *= 1.7; }
    step = 0.25;
    while (g.lambda(k, s, hi) > c) { hi += step; step *= 1.7; }
    // Newton with bisection safeguard
    p = 0.5 * (lo + hi);
    for (int it = 0; it < 100; ++it) {
        double fv = g.lambda(k, s, p) - c;
        if (fv > 0) lo = p; else hi = p;
        double dp = fv / g.dlambda(p);  // Newton step (dlambda < 0)
        double pn = p - dp;
        if (!(pn > lo && pn < hi)) pn = 0.5 * (lo + hi);
        if (std::fabs(pn - p) < 1e-13) { p = pn; break; }
        p = pn;
    }
    return p;
}

// Solve chi(k): a*I(0,chi) = (k-1)*pi*m, eq. (3.3).
static double solveChi(const GearPair& g, int k) {
    double target = (k - 1) * PI * g.m / g.a;
    double p = (k - 1) * 2.0 * PI / g.z;  // initial guess
    for (int it = 0; it < 60; ++it) {
        double fv = g.Ival(0.0, p) - target;
        double dp = fv / g.integrand(p);
        p -= dp;
        if (std::fabs(dp) < 1e-14) break;
    }
    return p;
}

// Singular point phi_S of the flank involute, eq. (5.2)/(5.11):
//   lambda_{k,s}(phi) * kappa(phi) = s * tan(alpha).
// The cusp lies on the root side of the flank: scan from lambda = 0 towards
// the root and take the first sign change.
static std::optional<double> solveCusp(const GearPair& g, bool driven, int k, int s,
                                       double lamRootSign, double lamScanMax) {
    double p0 = lambdaInv(g, k, s, 0.0);
    double pEnd = lambdaInv(g, k, s, lamRootSign * lamScanMax);
    int N = 600;
    auto F = [&](double p) {
        return g.lambda(k, s, p) * g.curvature(driven, p) - s * std::tan(g.alpha);
    };
    double pa = p0, fa = F(pa);
    for (int i = 1; i <= N; ++i) {
        double pb = p0 + (pEnd - p0) * i / N;
        double fb = F(pb);
        if (fa == 0.0) return pa;
        if (fa * fb < 0.0) {  // bisection refine
            double lo = pa, hi = pb, flo = fa;
            for (int it = 0; it < 80; ++it) {
                double mid = 0.5 * (lo + hi), fm = F(mid);
                if (flo * fm <= 0.0) hi = mid; else { lo = mid; flo = fm; }
            }
            return 0.5 * (lo + hi);
        }
        pa = pb; fa = fb;
    }
    return std::nullopt;
}

// ---------------------------------------------------------------------------
// CGAL-based intersection of two sampled parametric curves.
// Returns all transversal intersections as (u, v, point), Newton-polished.
// ---------------------------------------------------------------------------
struct CurveHit { double u, v; cplx pt; };

static std::vector<CurveHit> intersectCurves(
    const std::function<cplx(double)>& A, double u0, double u1, int nA,
    const std::function<cplx(double)>& B, double v0, double v1, int nB)
{
    std::vector<cplx> pa(nA + 1), pb(nB + 1);
    std::vector<double> ua(nA + 1), vb(nB + 1);
    for (int i = 0; i <= nA; ++i) { ua[i] = u0 + (u1 - u0) * i / nA; pa[i] = A(ua[i]); }
    for (int j = 0; j <= nB; ++j) { vb[j] = v0 + (v1 - v0) * j / nB; pb[j] = B(vb[j]); }

    std::vector<CurveHit> hits;
    for (int i = 0; i < nA; ++i) {
        double axlo = std::min(pa[i].real(), pa[i + 1].real());
        double axhi = std::max(pa[i].real(), pa[i + 1].real());
        double aylo = std::min(pa[i].imag(), pa[i + 1].imag());
        double ayhi = std::max(pa[i].imag(), pa[i + 1].imag());
        for (int j = 0; j < nB; ++j) {
            double bxlo = std::min(pb[j].real(), pb[j + 1].real());
            double bxhi = std::max(pb[j].real(), pb[j + 1].real());
            double bylo = std::min(pb[j].imag(), pb[j + 1].imag());
            double byhi = std::max(pb[j].imag(), pb[j + 1].imag());
            if (axhi < bxlo || bxhi < axlo || ayhi < bylo || byhi < aylo) continue;
            // exact intersection with CGAL
            ESeg sa(EPoint(pa[i].real(), pa[i].imag()), EPoint(pa[i + 1].real(), pa[i + 1].imag()));
            ESeg sb(EPoint(pb[j].real(), pb[j].imag()), EPoint(pb[j + 1].real(), pb[j + 1].imag()));
            auto res = CGAL::intersection(sa, sb);
            if (!res) continue;
            const EPoint* ip = boost::get<EPoint>(&*res);
            if (!ip) continue;  // ignore collinear-overlap degeneracies
            cplx P(CGAL::to_double(ip->x()), CGAL::to_double(ip->y()));
            // parameter interpolation within the segments
            cplx da = pa[i + 1] - pa[i], db = pb[j + 1] - pb[j];
            double ta = std::norm(da) > 0 ? ((P - pa[i]) * std::conj(da)).real() / std::norm(da) : 0.0;
            double tb = std::norm(db) > 0 ? ((P - pb[j]) * std::conj(db)).real() / std::norm(db) : 0.0;
            double u = ua[i] + ta * (ua[i + 1] - ua[i]);
            double v = vb[j] + tb * (vb[j + 1] - vb[j]);
            // Newton polish on G(u,v) = A(u) - B(v) with FD Jacobian
            for (int it = 0; it < 8; ++it) {
                cplx G = A(u) - B(v);
                double hu = 1e-7 * (1.0 + std::fabs(u)), hv = 1e-7 * (1.0 + std::fabs(v));
                cplx Au = (A(u + hu) - A(u - hu)) / (2.0 * hu);
                cplx Bv = (B(v + hv) - B(v - hv)) / (2.0 * hv);
                double j11 = Au.real(), j12 = -Bv.real();
                double j21 = Au.imag(), j22 = -Bv.imag();
                double det = j11 * j22 - j12 * j21;
                if (std::fabs(det) < 1e-18) break;
                double du = (G.real() * j22 - G.imag() * j12) / det;
                double dv = (j11 * G.imag() - j21 * G.real()) / det;
                u -= du; v -= dv;
                if (std::fabs(du) + std::fabs(dv) < 1e-13) break;
            }
            // avoid duplicates from shared segment endpoints
            bool dup = false;
            for (auto& h : hits)
                if (std::fabs(h.u - u) < 1e-9 && std::fabs(h.v - v) < 1e-9) { dup = true; break; }
            if (!dup) hits.push_back({u, v, A(u)});
        }
    }
    return hits;
}

// ---------------------------------------------------------------------------
// Tooth trimming parameters (Section 7 of the paper).
// ---------------------------------------------------------------------------
struct FlankTrim {
    double phiF_root, phiF_tip;   // flank curve parameter range
    double phiA_junc, phiA_ded;   // fillet curve: flank junction / dedendum contact
    double phiTip_add;            // parameter of the tip point on the addendum curve
    bool undercut = false;
    double phiS = 0.0, kappaS = 0.0;
};

static FlankTrim trimFlank(const GearPair& g, bool driven, int k, int s) {
    double sg = driven ? -1.0 : 1.0;
    double sec = 1.0 / std::cos(g.alpha), csc = 1.0 / std::sin(g.alpha), tn = std::tan(g.alpha);
    double lamBhat = ((g.hf - g.rho) * csc + g.rho) * sec;        // |lambda| at (5.3)/(5.12)
    double lamDhat = (g.hf - g.rho) * tn + g.rho * sec;           // |lambda| at (3.32)/(4.19)
    double lamHhat = g.ha / (std::sin(g.alpha) * std::cos(g.alpha)); // |lambda| near the tip

    double lamTip  = sg * s * lamHhat;
    double lamRoot = -sg * s * lamBhat;   // contact point of flank and fillet, (5.3)/(5.12)
    double lamDed  = -sg * s * lamDhat;   // contact point of fillet and dedendum

    FlankTrim T;
    T.phiA_ded = lambdaInv(g, k, s, lamDed);

    // cusp (singular point of the involute), eq. (5.2)/(5.11)
    double rootSign = (lamRoot > 0) ? 1.0 : -1.0;
    auto cusp = solveCusp(g, driven, k, s, rootSign, 2.2 * lamBhat);
    double phiB = lambdaInv(g, k, s, lamRoot);
    bool uc = false;
    if (cusp) {
        T.phiS = *cusp;
        T.kappaS = g.curvature(driven, T.phiS);
        double lamS = g.lambda(k, s, T.phiS);
        uc = std::fabs(lamS) < lamBhat;   // phi_B beyond the cusp => undercut
    }
    T.undercut = uc;

    // tip-side flank parameter limit for sampling (a bit past the addendum)
    double phiTipExt = lambdaInv(g, k, s, lamTip * 1.30);
    double phiRootSample = uc ? *cusp : phiB;

    auto flankFn = [&](double p) { return g.flank(driven, k, s, p); };
    auto filletFn = [&](double p) { return g.fillet(driven, k, s, p); };
    auto addFn = [&](double p) { return g.offsetCurve(driven, g.ha, p); };

    int dir = (phiTipExt > phiRootSample) ? 1 : -1;  // flank traversal direction in phi

    // --- root junction ---
    if (!uc) {
        T.phiF_root = phiB;       // (7.3)/(7.6): contact at the same parameter
        T.phiA_junc = phiB;
    } else {
        // flank x fillet intersection, eqs. (7.1)/(7.4)/(7.10)/(7.13)
        double fil0 = T.phiA_ded;
        double fil1 = lambdaInv(g, k, s, -sg * s * 1.6 * lamBhat);
        auto hits = intersectCurves(flankFn, phiRootSample, phiTipExt, 1500,
                                    filletFn, fil0, fil1, 900);
        if (!hits.empty()) {
            // keep the intersection closest to the tip on the valid involute branch
            auto best = hits[0];
            for (auto& h : hits)
                if (dir * h.u > dir * best.u) best = h;
            T.phiF_root = best.u;
            T.phiA_junc = best.v;
        } else {
            // Marginal undercut: the fillet curve is tangent to the *folded*
            // involute branch just past the cusp (at phi_B, where eq. (7.1)
            // is satisfied exactly) but does not transversally cross the
            // valid branch.  Trim the flank at its cusp and the fillet at
            // phi_B; the remaining gap is the size of the boundary
            // micro-fold (order 1e-3 * m) and is closed with a chord.
            T.phiF_root = *cusp;
            T.phiA_junc = phiB;
        }
    }

    // --- tip: flank x addendum curve, eqs. (7.2)/(7.5)/(7.11)/(7.14) ---
    {
        // addendum window: half a pitch to each side of the tooth centre
        double w0 = lambdaInv(g, k, s, s * PI * g.m / 4.0 + PI * g.m / 2.0);
        double w1 = lambdaInv(g, k, s, s * PI * g.m / 4.0 - PI * g.m / 2.0);
        if (w0 > w1) std::swap(w0, w1);
        auto hits = intersectCurves(flankFn, T.phiF_root, phiTipExt, 1500,
                                    addFn, w0, w1, 900);
        if (hits.empty())
            throw std::runtime_error("flank/addendum intersection not found");
        auto best = hits[0];
        for (auto& h : hits)  // first crossing along the flank from root to tip
            if (dir * h.u < dir * best.u) best = h;
        T.phiF_tip = best.u;
        T.phiTip_add = best.v;
    }
    return T;
}

// ---------------------------------------------------------------------------
// Profile assembly
// ---------------------------------------------------------------------------
struct ToothTrims { FlankTrim minus, plus; };

static void sampleArc(std::vector<cplx>& out, const std::function<cplx(double)>& C,
                      double p0, double p1, double ptsPerRad) {
    int n = std::max(6, (int)std::ceil(std::fabs(p1 - p0) * ptsPerRad));
    for (int i = 0; i <= n; ++i) {
        cplx p = C(p0 + (p1 - p0) * i / n);
        if (!out.empty() && std::abs(p - out.back()) < 1e-9) continue;
        out.push_back(p);
    }
}

// Clip micro-loops: where the boundary folds back on itself over a short
// stretch (parallel-curve cusp pairs at osculating flank/fillet junctions,
// marginal-undercut chords), replace the loop with the self-intersection
// point.  This is exactly the local boundary-of-union operation.  Loops
// larger than maxDiam are left alone (and will fail the simplicity check).
static std::vector<cplx> clipMicroLoops(std::vector<cplx> pts, int window,
                                        double maxDiam, int* nClipped, double* maxClip) {
    *nClipped = 0; *maxClip = 0.0;
    bool changed = true;
    while (changed) {
        changed = false;
        int n = (int)pts.size();
        for (int i = 0; i < n - 2 && !changed; ++i) {
            int jmax = std::min(i + window, n - 1 - (i == 0 ? 1 : 0));
            for (int j = i + 2; j <= jmax; ++j) {
                const cplx &a1 = pts[i], &a2 = pts[i + 1], &b1 = pts[j], &b2 = pts[(j + 1) % n];
                double d1x = a2.real() - a1.real(), d1y = a2.imag() - a1.imag();
                double d2x = b2.real() - b1.real(), d2y = b2.imag() - b1.imag();
                double den = d1x * d2y - d1y * d2x;
                if (den == 0.0) continue;
                double wx = b1.real() - a1.real(), wy = b1.imag() - a1.imag();
                double t = (wx * d2y - wy * d2x) / den;
                double u = (wx * d1y - wy * d1x) / den;
                if (t < 0.0 || t > 1.0 || u < 0.0 || u > 1.0) continue;
                cplx X(a1.real() + t * d1x, a1.imag() + t * d1y);
                // diameter of the loop pts[i+1..j]
                double diam = 0.0;
                for (int q = i + 1; q <= j; ++q) diam = std::max(diam, std::abs(pts[q] - X));
                if (diam > maxDiam) continue;
                std::vector<cplx> np(pts.begin(), pts.begin() + i + 1);
                np.push_back(X);
                np.insert(np.end(), pts.begin() + j + 1, pts.end());
                pts.swap(np);
                ++*nClipped; *maxClip = std::max(*maxClip, diam);
                changed = true;
                break;
            }
        }
    }
    return pts;
}

static std::vector<cplx> assembleProfile(const GearPair& g, bool driven,
                                         const std::vector<ToothTrims>& tt,
                                         double ptsPerRad) {
    std::vector<cplx> pts;
    int z = g.z;
    auto dedFn = [&](double p) { return g.offsetCurve(driven, -g.hf, p); };
    auto addFn = [&](double p) { return g.offsetCurve(driven, g.ha, p); };
    for (int k = 1; k <= z; ++k) {
        const FlankTrim& M = tt[k - 1].minus;
        const FlankTrim& P = tt[k - 1].plus;
        auto flankM  = [&](double p) { return g.flank(driven, k, -1, p); };
        auto flankP  = [&](double p) { return g.flank(driven, k, +1, p); };
        auto filletM = [&](double p) { return g.fillet(driven, k, -1, p); };
        auto filletP = [&](double p) { return g.fillet(driven, k, +1, p); };
        const FlankTrim& Mn = tt[k % z].minus;  // next tooth, "-" side
        const FlankTrim& Pn = tt[k % z].plus;
        double wrap = (k == z) ? 2.0 * PI : 0.0;

        if (!driven) {
            // tooth k of the drive gear:
            // fillet- (ded -> flank), flank- (root -> tip), addendum,
            // flank+ (tip -> root), fillet+ (flank -> ded), dedendum to k+1
            sampleArc(pts, filletM, M.phiA_ded, M.phiA_junc, ptsPerRad);
            sampleArc(pts, flankM, M.phiF_root, M.phiF_tip, ptsPerRad);
            sampleArc(pts, addFn, M.phiTip_add, P.phiTip_add, ptsPerRad);
            sampleArc(pts, flankP, P.phiF_tip, P.phiF_root, ptsPerRad);
            sampleArc(pts, filletP, P.phiA_junc, P.phiA_ded, ptsPerRad);
            sampleArc(pts, dedFn, P.phiA_ded, Mn.phiA_ded + wrap, ptsPerRad);
        } else {
            // tooth space k of the driven gear:
            // flank- (tip -> root), fillet- (flank -> ded), dedendum,
            // fillet+ (ded -> flank), flank+ (root -> tip), addendum to k+1
            sampleArc(pts, flankM, M.phiF_tip, M.phiF_root, ptsPerRad);
            sampleArc(pts, filletM, M.phiA_junc, M.phiA_ded, ptsPerRad);
            sampleArc(pts, dedFn, M.phiA_ded, P.phiA_ded, ptsPerRad);
            sampleArc(pts, filletP, P.phiA_ded, P.phiA_junc, ptsPerRad);
            sampleArc(pts, flankP, P.phiF_root, P.phiF_tip, ptsPerRad);
            sampleArc(pts, addFn, P.phiTip_add, Mn.phiTip_add + wrap, ptsPerRad);
        }
    }
    if (!pts.empty() && std::abs(pts.front() - pts.back()) < 1e-7) pts.pop_back();
    return pts;
}

// ---------------------------------------------------------------------------
// CGAL polygon validation: simplicity and meshing interference.
// ---------------------------------------------------------------------------
static EPoly toPolygon(const std::vector<cplx>& pts) {
    EPoly P;
    for (auto& p : pts) P.push_back(EPoint(p.real(), p.imag()));
    if (P.orientation() == CGAL::CLOCKWISE) P.reverse_orientation();
    return P;
}

static double overlapArea(const EPoly& A, const EPoly& B) {
    std::vector<EPwh> out;
    CGAL::intersection(A, B, std::back_inserter(out));
    double area = 0.0;
    for (auto& pwh : out) {
        area += CGAL::to_double(pwh.outer_boundary().area());
        for (auto h = pwh.holes_begin(); h != pwh.holes_end(); ++h)
            area -= std::fabs(CGAL::to_double(h->area()));
    }
    return area;
}

static EPoly transformed(const std::vector<cplx>& pts, cplx rot, cplx shift) {
    EPoly P;
    for (auto& p : pts) {
        cplx q = rot * p + shift;
        P.push_back(EPoint(q.real(), q.imag()));
    }
    if (P.orientation() == CGAL::CLOCKWISE) P.reverse_orientation();
    return P;
}

// ---------------------------------------------------------------------------
// JSON output
// ---------------------------------------------------------------------------
static void writePts(FILE* fp, const char* key, const std::vector<cplx>& pts) {
    fprintf(fp, "\"%s\":[", key);
    for (size_t i = 0; i < pts.size(); ++i)
        fprintf(fp, "%s[%.10g,%.10g]", i ? "," : "", pts[i].real(), pts[i].imag());
    fprintf(fp, "]");
}

// ---------------------------------------------------------------------------
// Driver
// ---------------------------------------------------------------------------
struct SampleSpec {
    std::string name;
    TransFn f;
    int z;
    double m, alphaDeg, haf, hff, rhof;  // ha/hf/rho as multiples of m
};

static void runSample(const SampleSpec& spec, const std::string& outDir) {
    GearPair g;
    g.f = spec.f; g.z = spec.z; g.m = spec.m;
    g.alpha = spec.alphaDeg * PI / 180.0;
    g.ha = spec.haf * g.m; g.hf = spec.hff * g.m; g.rho = spec.rhof * g.m;

    printf("=== sample '%s': psi = %s, z=%d, m=%g, alpha=%g deg ===\n",
           spec.name.c_str(), g.f.desc.c_str(), g.z, g.m, spec.alphaDeg);

    // Step 1: convexity check of both centrodes (kappa <= 0, kappa~ >= 0).
    g.a = 1.0;
    double kmax = -1e9, ktmin = 1e9;
    for (int i = 0; i <= 2000; ++i) {
        double p = 2.0 * PI * i / 2000;
        kmax = std::max(kmax, g.curvature(false, p));
        ktmin = std::min(ktmin, g.curvature(true, p));
    }
    printf("centrode check (a=1): max kappa_drive = %.6g (need <= 0), "
           "min kappa_driven = %.6g (need >= 0)\n", kmax, ktmin);
    if (kmax > 1e-9 || ktmin < -1e-9)
        throw std::runtime_error("centrode not convex - choose different psi/b");

    // Steps 2-3: I(0,2pi) and pivot distance a (2.14).
    double I2pi = g.Ival(0.0, 2.0 * PI);
    g.a = g.z * PI * g.m / I2pi;
    printf("I(0,2pi) = %.6f   a = %.6f\n", I2pi, g.a);

    // Step 5: chi(k) from (3.3).
    g.chi.resize(g.z);
    for (int k = 1; k <= g.z; ++k) g.chi[k - 1] = solveChi(g, k);
    printf("chi(k): ");
    for (int k = 1; k <= g.z; ++k) printf("%.6g ", g.chi[k - 1]);
    printf("\n");

    // Steps 6-9 / 13-16 for both gears.
    double ucLimit = std::sin(g.alpha) * std::sin(g.alpha)
                   / (g.hf - g.rho * (1.0 - std::sin(g.alpha)));  // (5.5)/(5.13)
    std::vector<cplx> profiles[2];
    std::vector<std::vector<ToothTrims>> alltrims(2);
    for (int gi = 0; gi < 2; ++gi) {
        bool driven = (gi == 1);
        auto& trims = alltrims[gi];
        trims.resize(g.z);
        int nUC = 0;
        for (int k = 1; k <= g.z; ++k) {
            trims[k - 1].minus = trimFlank(g, driven, k, -1);
            trims[k - 1].plus  = trimFlank(g, driven, k, +1);
            nUC += trims[k - 1].minus.undercut + trims[k - 1].plus.undercut;
        }
        printf("%s gear: undercut on %d of %d flanks (criterion |kappa(phi_S)| <= %.6g)\n",
               driven ? "driven" : "drive", nUC, 2 * g.z, ucLimit);
        if (spec.name == "fig83" && !driven) {
            printf("  singular points (cf. paper Table 8.2):\n");
            for (int k = 1; k <= g.z; ++k)
                printf("   k=%2d  phiS-=% .6f k-=% .7f UC-=%d   phiS+=% .6f k+=% .7f UC+=%d\n",
                       k, trims[k-1].minus.phiS, trims[k-1].minus.kappaS, trims[k-1].minus.undercut,
                       trims[k-1].plus.phiS, trims[k-1].plus.kappaS, trims[k-1].plus.undercut);
        }
        profiles[gi] = assembleProfile(g, driven, trims, 220.0);
        int nClip = 0; double maxClip = 0.0;
        profiles[gi] = clipMicroLoops(profiles[gi], 300, 0.10 * g.m, &nClip, &maxClip);
        if (nClip)
            printf("%s gear: clipped %d boundary micro-fold(s), max diameter %.4g\n",
                   driven ? "driven" : "drive", nClip, maxClip);
        EPoly poly = toPolygon(profiles[gi]);
        printf("%s gear profile: %zu points, simple polygon: %s, area = %.4f\n",
               driven ? "driven" : "drive", profiles[gi].size(),
               poly.is_simple() ? "yes" : "NO", CGAL::to_double(poly.area()));
        if (!poly.is_simple()) {
            FILE* dbg = fopen("/tmp/bad_profile.csv", "w");
            for (auto& q : profiles[gi]) fprintf(dbg, "%.12g,%.12g\n", q.real(), q.imag());
            fclose(dbg);
            throw std::runtime_error("assembled profile is not a simple polygon (dumped)");
        }
    }

    // Meshing interference check over a set of poses (CGAL Boolean ops).
    int nPoses = 12;
    std::vector<double> posePhi(nPoses), posePsi(nPoses), poseOvl(nPoses);
    double maxOvl = 0.0;
    for (int j = 0; j < nPoses; ++j) {
        double p0 = 2.0 * PI * j / nPoses + 0.123;  // arbitrary offset, avoids symmetry
        double ps = g.f.psi(p0);
        EPoly A = transformed(profiles[0], std::exp(I * p0), cplx(0, 0));
        EPoly B = transformed(profiles[1], std::exp(-I * ps), cplx(g.a, 0));
        double ov = overlapArea(A, B);
        posePhi[j] = p0; posePsi[j] = ps; poseOvl[j] = ov;
        maxOvl = std::max(maxOvl, ov);
    }
    printf("meshing check over %d poses: max overlap area = %.3e (module^2 = %.3g)\n",
           nPoses, maxOvl, g.m * g.m);

    // JSON export for rendering.
    std::string path = outDir + "/" + spec.name + ".json";
    FILE* fp = fopen(path.c_str(), "w");
    if (!fp) throw std::runtime_error("cannot write " + path);
    fprintf(fp, "{\"name\":\"%s\",\"psi\":\"%s\",\"a\":%.10g,\"m\":%g,\"z\":%d,"
                "\"alpha_deg\":%g,\"ha\":%g,\"hf\":%g,\"rho\":%g,",
            spec.name.c_str(), g.f.desc.c_str(), g.a, g.m, g.z,
            spec.alphaDeg, g.ha, g.hf, g.rho);
    for (int gi = 0; gi < 2; ++gi) {
        bool driven = (gi == 1);
        std::vector<cplx> cen, add, ded;
        for (int i = 0; i <= 1440; ++i) {
            double p = 2.0 * PI * i / 1440;
            cen.push_back(g.centrode(driven, p));
            add.push_back(g.offsetCurve(driven, g.ha, p));
            ded.push_back(g.offsetCurve(driven, -g.hf, p));
        }
        fprintf(fp, "\"%s\":{", driven ? "driven" : "drive");
        writePts(fp, "profile", profiles[gi]); fprintf(fp, ",");
        writePts(fp, "centrode", cen); fprintf(fp, ",");
        writePts(fp, "addendum", add); fprintf(fp, ",");
        writePts(fp, "dedendum", ded);
        fprintf(fp, "},");
    }
    fprintf(fp, "\"poses\":[");
    for (int j = 0; j < nPoses; ++j)
        fprintf(fp, "%s{\"phi\":%.10g,\"psi\":%.10g,\"overlap\":%.6g,\"r\":%.10g}",
                j ? "," : "", posePhi[j], posePsi[j], poseOvl[j], g.r(posePhi[j]));
    fprintf(fp, "]}\n");
    fclose(fp);
    printf("wrote %s\n\n", path.c_str());

    // Numerical cross-check against the paper for the fig. 8.3 sample.
    if (spec.name == "fig83") {
        const double chiRef[14] = {0, 0.674065, 1.18877, 1.63010, 2.03297, 2.41317,
                                   2.78037, PI, 3.50282, 3.87002, 4.25022, 4.65309,
                                   5.09441, 5.60912};
        double dchi = 0;
        for (int k = 0; k < 14; ++k) dchi = std::max(dchi, std::fabs(g.chi[k] - chiRef[k]));
        printf("[fig83 validation] I(0,2pi) ref 3.09315 -> %.5f ; a ref 28.4385 -> %.4f ; "
               "max |chi - Table 8.1| = %.2e\n", I2pi, g.a, dchi);
        const double phiSref[14] = {-0.662309, -0.370208, 0.697105, 1.23593, 1.64804,
                                    2.02344, 2.38300, 2.73727, 3.09339, 3.45764,
                                    3.83688, 4.23933, 4.67392, 5.14546};
        double dphiS = 0;
        for (int k = 0; k < 14; ++k)
            dphiS = std::max(dphiS, std::fabs(alltrims[0][k].minus.phiS - phiSref[k]));
        printf("[fig83 validation] max |phiS_minus - Table 8.2| = %.2e\n\n", dphiS);
    }
}

int main(int argc, char** argv) {
    std::string outDir = argc > 1 ? argv[1] : "out";
    const double b1 = 2.0 - std::sqrt(2.0);
    std::vector<SampleSpec> samples = {
        // sanity check: constant ratio -> ordinary circular involute gears
        {"circular", sineTransmission(0.0, 1, "phi (b=0, circular)"), 12, 2.0, 20.0, 1.0, 1.2, 0.3},
        // the example of the paper, Fig. 8.3
        {"fig83", sineTransmission(b1, 1, "phi-(2-sqrt2)sin(phi)"), 14, 2.0, 20.0, 1.0, 1.2, 0.3},
        // two-lobed ("oval") gears: psi' has period pi
        {"oval2", sineTransmission(0.28, 2, "phi-0.14sin(2phi)"), 18, 2.0, 20.0, 1.0, 1.2, 0.3},
        // three-lobed gears: psi' has period 2pi/3
        {"lobe3", sineTransmission(0.16, 3, "phi-0.0533sin(3phi)"), 24, 2.0, 20.0, 1.0, 1.2, 0.3},
    };
    for (auto& s : samples) {
        try {
            runSample(s, outDir);
        } catch (const std::exception& e) {
            fprintf(stderr, "sample %s FAILED: %s\n", s.name.c_str(), e.what());
            return 1;
        }
    }
    return 0;
}
