#!/usr/bin/env python3
"""Render PNGs of the gear pairs generated by gear_gen (JSON in out/)."""
import json
import math
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


def rot(pts, ang):
    c, s = math.cos(ang), math.sin(ang)
    return pts @ np.array([[c, s], [-s, c]]).T  # multiply complex e^{i ang}


def closed(pts):
    return np.vstack([pts, pts[:1]])


def draw_pair(ax, d, phi, psi, fill=True, lw=0.8):
    a = d["a"]
    drv = rot(np.asarray(d["drive"]["profile"]), phi)
    dvn = rot(np.asarray(d["driven"]["profile"]), -psi) + [a, 0]
    cd = rot(np.asarray(d["drive"]["centrode"]), phi)
    cv = rot(np.asarray(d["driven"]["centrode"]), -psi) + [a, 0]
    if fill:
        ax.fill(*closed(drv).T, color="#cfe8cf", zorder=1)
        ax.fill(*closed(dvn).T, color="#cfe0f0", zorder=1)
    ax.plot(*closed(drv).T, color="#1a7a1a", lw=lw, zorder=3)
    ax.plot(*closed(dvn).T, color="#1a4a7a", lw=lw, zorder=3)
    ax.plot(*closed(cd).T, "--", color="#888", lw=0.6, zorder=2)
    ax.plot(*closed(cv).T, "--", color="#888", lw=0.6, zorder=2)
    ax.plot([0, a], [0, 0], "k+", ms=10, zorder=4)
    ax.set_aspect("equal")


def render(jpath, outdir):
    d = json.loads(Path(jpath).read_text())
    name = d["name"]

    # ---- figure 1: pair at pose 0 (cf. paper Fig. 8.3) ----
    fig, ax = plt.subplots(figsize=(11, 6.5))
    draw_pair(ax, d, 0.0, 0.0)
    ax.set_title(f"{name}:  $\\psi(\\varphi)$ = {d['psi']},  z={d['z']}, m={d['m']}, "
                 f"$\\alpha$={d['alpha_deg']}$^\\circ$, a={d['a']:.4f}")
    ax.grid(alpha=0.2, lw=0.4)
    fig.tight_layout()
    fig.savefig(Path(outdir) / f"{name}_pair.png", dpi=160)
    plt.close(fig)

    # ---- figure 2: each gear alone with reference curves ----
    fig, axes = plt.subplots(1, 2, figsize=(13, 6.5))
    for ax, key, col in [(axes[0], "drive", "#1a7a1a"), (axes[1], "driven", "#1a4a7a")]:
        gd = d[key]
        prof = np.asarray(gd["profile"])
        ax.fill(*closed(prof).T, color="#eee", zorder=1)
        ax.plot(*closed(prof).T, color=col, lw=0.8, zorder=4)
        ax.plot(*closed(np.asarray(gd["centrode"])).T, "--", color="#c33", lw=0.7,
                zorder=3, label="centrode (pitch curve)")
        ax.plot(*closed(np.asarray(gd["addendum"])).T, ":", color="#999", lw=0.6,
                zorder=2, label="addendum/dedendum curves")
        ax.plot(*closed(np.asarray(gd["dedendum"])).T, ":", color="#999", lw=0.6, zorder=2)
        ax.plot(0, 0, "k+", ms=10)
        ax.set_aspect("equal")
        ax.set_title(f"{name}: {key} gear")
        ax.legend(loc="upper right", fontsize=8)
        ax.grid(alpha=0.2, lw=0.4)
    fig.tight_layout()
    fig.savefig(Path(outdir) / f"{name}_gears.png", dpi=160)
    plt.close(fig)

    # ---- figure 3: meshing poses with zoom on the contact zone ----
    poses = d["poses"][::2][:6]
    fig, axes = plt.subplots(2, len(poses), figsize=(3.2 * len(poses), 7.2),
                             gridspec_kw={"height_ratios": [1.35, 1]})
    for j, pose in enumerate(poses):
        axt, axb = axes[0, j], axes[1, j]
        draw_pair(axt, d, pose["phi"], pose["psi"], lw=0.5)
        axt.set_title(f"$\\varphi$={pose['phi']:.2f}  ovl={pose['overlap']:.1e}",
                      fontsize=8)
        axt.set_xticks([]); axt.set_yticks([])
        draw_pair(axb, d, pose["phi"], pose["psi"], lw=0.7)
        r = pose["r"]
        wz = 3.5 * d["m"]
        axb.set_xlim(r - wz, r + wz); axb.set_ylim(-wz, wz)
        axb.set_xticks([]); axb.set_yticks([])
        axb.set_title("pitch-point zoom", fontsize=8)
    fig.suptitle(f"{name}: meshing check (drive rotated by $\\varphi$, "
                 f"driven by $-\\psi(\\varphi)$); CGAL overlap area per pose", fontsize=11)
    fig.tight_layout(rect=[0, 0, 1, 0.96])
    fig.savefig(Path(outdir) / f"{name}_mesh.png", dpi=150)
    plt.close(fig)
    print(f"rendered {name}")


if __name__ == "__main__":
    outdir = sys.argv[2] if len(sys.argv) > 2 else "samples"
    Path(outdir).mkdir(exist_ok=True)
    src = Path(sys.argv[1] if len(sys.argv) > 1 else "out")
    for j in sorted(src.glob("*.json")):
        render(j, outdir)
